import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/ThemeProvider";
// import NavbarClient from "@/components/NavbarClient";
import { LanguageProvider } from "@/context/LanguageContext";
import { Footer2 } from "@/components/footer2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <h1>This is root layout</h1> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange // when toggling happens, this will change
        >
          <LanguageProvider>
            {children}
            {/* <NavbarClient /> */}
          </LanguageProvider>
          {/* <Toaster richColors position="top-center" /> */}
        </ThemeProvider>
        <Footer2 />
      </body>
    </html>
  );
}

